### ISSUE TITLE
This boilerplate works on Windows.

### ISSUE THREAD

**Issue by movpushmov** [abbl/electron-typescript-react-typeorm-sqlite-boilerplate#25]
Proofs:
![image](https://user-images.githubusercontent.com/49155506/132945521-6b5788e4-3901-43fc-a9d6-b6aeb7b9da3e.png)

Windows 10 21H1

**Comment by movpushmov** [comment]
@abbl

**Comment by przucidlo** [comment]
Hey Edward

Thanks a lot for your feedback, I've updated the readme file in commit 998600c. 

I will now close the issue, thanks again!
